add double quotes to data selector values
cypress-io/unique-selector pull request #2
Opened 2021-10-23 04:06 UTC by Manuel-Suarez-Abascal

**What was changed with this Pull Request?**

- Added `method` to check for `data attributes selectors` without `double quotes` & wrap `double quotes` around them.
- Updated `unit` tests.
- Fixed small typo 😉 

**Why was this change needed?**

It was to resolve a bug in the `Cypress Playground Selector` [here](https://github.com/cypress-io/cypress/issues/1884).

**Passing unit tests**

<img width="813" alt="Screen Shot 2021-10-22 at 11 46 48 PM" src="https://user-images.githubusercontent.com/32891808/138541797-c67a63b0-1779-4560-b34c-b02382011413.png">

2021-10-23 04:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/unique-selector?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/unique-selector?pullRequest=2) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Manuel-Suarez-Abascal<br/>:x: chrisbreiding<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/unique-selector?pullRequest=2) it.</sub>

2021-10-25 14:01 UTC, chrisbreiding requested changes

2021-10-25 14:01 UTC, chrisbreiding commented on src/getData.js
> +      return _setQuotesToAttrSelector(`[${nodeName}]`);
Maybe I'm missing something, but it seems this can be simplified a good bit. Should be able to get rid of the `if (needsQuote( value ) )` check and always add quotes around the value. Then `_setQuotesToAttrSelector` won't be necessary at all. Also don't have to worry about the case where there is no value.

2021-10-27 22:21 UTC, Manuel-Suarez-Abascal commented on src/getData.js
> +      return _setQuotesToAttrSelector(`[${nodeName}]`);
@chrisbreiding I have addressed your PR comments. Can you take another look it at?

> Also don't have to worry about the case where there is no value.

I removed one of the unit tests which it was covering this edge case.

2021-10-28 20:04 UTC, BlueWinds commented on src/getData.js
> +      return _setQuotesToAttrSelector(`[${nodeName}]`);
@chrisbreiding - Can you explain to me why do don't need to worry about not having a value anymore? I'm a bit lacking on context for this, but it seems like it's still an important case to cover.

```
if ( nodeName === selectorType ) {
  return value ? `[${nodeName}="${value}"]` : `[${nodeName}]`
}
```

2021-11-01 13:23 UTC, chrisbreiding commented on src/getData.js
> +      return _setQuotesToAttrSelector(`[${nodeName}]`);
Sorry, my feedback wasn't clear. I meant that the attribute-only, value-less case doesn't need special handling in regards to quotes, so it should remain unchanged in this PR.

2021-11-01 13:25 UTC, chrisbreiding requested changes
Please add back support for selectors that are only an attribute with no value.

2021-11-09 20:53 UTC, chrisbreiding commented
Hey @Manuel-Suarez-Abascal, do you think you'll have a chance to address the review for this PR?

2021-11-09 23:33 UTC, Manuel-Suarez-Abascal commented
> Hey @Manuel-Suarez-Abascal, do you think you'll have a chance to address the review for this PR?

Hi, @chrisbreiding I might take a look at it again during the weekend! 🚀  I am a bit busy with work this week 😬

2021-11-15 07:29 UTC, Manuel-Suarez-Abascal commented on src/getData.js
> +      return _setQuotesToAttrSelector(`[${nodeName}]`);
@chrisbreiding I have addressed your PR comment. Could you take another look at it, please? Hopefully this time I got it right 😬 Also, all unit tests are passing.

<img width="815" alt="Screen Shot 2021-11-15 at 2 27 25 AM" src="https://user-images.githubusercontent.com/32891808/141739716-2fb782c1-e2e9-48c2-92e8-d8b2b196e5ac.png">

2021-11-15 07:31 UTC, Manuel-Suarez-Abascal commented on src/getData.js
> +      return _setQuotesToAttrSelector(`[${nodeName}]`);
Also, maybe for future improvement, we can add some linting rules to match the `cypress` repo? I think this repo will benefit from some linting rules :)

2021-11-16 15:16 UTC, merged